import React, { Suspense, useEffect, useState } from "react";
import Head from "next/head";
import { NextPage } from "next";
import HomePage from "@/components/pages/homePage/HomePage";

const IndexPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Klinika Laryngologiczna - Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Suspense fallback={<div>Loading ...</div>}>
          <HomePage />
        </Suspense>
      </main>
    </>
  );
};

export default IndexPage;
